version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./web/api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  api:
    build:
      context: ./api
    volumes:
      - ./public:/var/www/public
      - ./api/xdebug.ini:/etc/php/conf.d/xdebug.ini